#!/usr/bin/env node
global.ROOT = __dirname

const { ToteaServer } = require('../index')

class Server extends ToteaServer{
  customizeRouter(router) {
    router.get('/', (req, res, next) => {
      res.send('totea server is running!')
    })
  }

  customizeToTeaRouter(toteaRoute) {
    toteaRoute.injectUpload(['image'])
  }
}

new Server({
  mongoUri: 'mongodb://localhost:27017/totea',
  port: 3000
})
